version: '3'
services:
  handler:
    image: golang:1.21.3-bullseye
    container_name: "handler"
    volumes:
      - ./handler:/workspace:cached
    environment:
      - LB_ADDR=loadbrancer:3000
    tty: true

  loadbrancer:
    image: golang:1.21.3-bullseye
    container_name: "loadbrancer"
    volumes:
      - ./loadbrancer:/workspace:cached
    environment:
      - PORT=3000
      - EXPORTS=store1:3316,store2:3326
    ports:
      - "3000:3000"
    tty: true
    command:
      - 'sh'
      - '-c'
      - >-
        go run /workspace/main.go

  store1:
    image: golang:1.21.3-bullseye
    container_name: "store1"
    volumes:
      - ./store:/workspace:cached
    environment:
      - PORT=3316
    ports:
      - "3316:3316"
    tty: true
    command:
      - 'sh'
      - '-c'
      - >-
        cd /workspace && go mod tidy && go run main.go

  store2:
    image: golang:1.21.3-bullseye
    container_name: "store2"
    volumes:
      - ./store:/workspace:cached
    environment:
      - PORT=3326
    ports:
      - "3326:3326"
    tty: true
    command:
      - 'sh'
      - '-c'
      - >-
        cd /workspace && go mod tidy && go run main.go

  sync:
    image: golang:1.21.3-bullseye
    container_name: "sync"
    volumes:
      - ./sync:/workspace:cached
    environment:
      - PORT=8801
    ports:
      - "8801:8801"
    tty: true
    command:
      - 'sh'
      - '-c'
      - >-
        go run /workspace/main.go
